# Generated by Django 5.1.4 on 2024-12-29 06:29

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_options_alter_courses_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(null=True, upload_to=courses.models.handle_upload),
        ),
    ]
