[project]
name = "course-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-storages[s3]>=1.14.4",
    "django>=5.1,<5.2",
    "pillow>=11.0.0",
    "psycopg>=3.2.3",
    "django-environ>=0.11.2",
]
